### ISSUE TITLE
PHI-MVS: Plane Hypothesis Inference Multi-view Stereo for Large-Scale Scene Reconstruction

### ISSUE THREAD

**Issue by mingliangfu** [ss2lyf/PHI-MVS#1]
Is it official repo created for arxiv paper-PHI-MVS? If so, will the project be released in the near future？

**Comment by ss2lyf** [comment]
> Is it official repo created for arxiv paper-PHI-MVS? If so, will the project be released in the near future？

Yes, it is the official repo, our paper is under review and the code has not been sorted out yet.
